---
# argument spec file for damien_live.homelab.podman_app

argument_specs:
  main:
    short_description: >-
      Installs/runs all the different podman elements to an application including: 
      containers, networks, volumes, secrets and firewall services.
    description: "!#!FIXME description"
    options:
      podman_app_specs:
        type: dict
        description: A simple string argument for demonstration.
        required: true
        options:
          create_dirs:
            type: bool
            description: "!#!FIXME description"
            default: false
          start_containers:
            type: bool
            description: "!#!FIXME description"
            default: false
          networks:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          volumes:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          secrets:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          firewall_services:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          containers:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
        required: true
        options:
          create_dirs:
            type: bool
            description: "!#!FIXME description"
            default: false
          start_containers:
            type: bool
            description: "!#!FIXME description"
            default: false
          networks:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          volumes:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          secrets:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          firewall_services:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
          containers:
            type: list
            elements: dict
            description: "!#!FIXME description"
            default: []
